# Generated by Django 5.1.6 on 2025-03-16 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Faculti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название группы')),
                ('course', models.CharField(choices=[('11', '11'), ('11', '12'), ('21', '21'), ('22', '22'), ('31', '31'), ('32', '32'), ('41', '41'), ('42', '42'), ('51', '51'), ('52', '52')], default='11', max_length=2, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Kurator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.CharField(max_length=1, verbose_name='Номер пары')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало пары')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Конец пары')),
                ('start_time_1', models.TimeField(blank=True, null=True, verbose_name='Начало первой части')),
                ('end_time_1', models.TimeField(blank=True, null=True, verbose_name='Конец первой части')),
                ('start_time_2', models.TimeField(blank=True, null=True, verbose_name='Начало второй части')),
                ('end_time_2', models.TimeField(blank=True, null=True, verbose_name='Конец второй части')),
            ],
            options={
                'verbose_name': 'Время пары',
                'verbose_name_plural': 'Времена пар',
                'ordering': ['lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('news', models.TextField(verbose_name='Новость')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Предмет')),
                ('teacher', models.CharField(max_length=100, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Оценка')),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, default='./static/media/no_avatar.jpeg', null=True, upload_to='./teacher_avatars/')),
                ('faculti', models.CharField(choices=[('Факультет топлива и экологии', 'Факультет топлива и экологии'), ('Механический факультет', 'Механический факультет'), ('Факультет информационных технологий и экономики', 'Факультет информационных технологий и экономики'), ('Энергетический факультет', 'Энергетический факультет'), ('Заочный факультет', 'Заочный факультет'), ('Факультет сервиса', 'Факультет сервиса'), ('Факультет техносферной безопасности и права', 'Факультет техносферной безопасности и права')], max_length=255)),
                ('subjects', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups', verbose_name='Группа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiy', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('otchestvo', models.CharField(max_length=255, verbose_name='Отчество')),
                ('faculti', models.CharField(choices=[('Факультет топлива и экологии', 'Факультет топлива и экологии'), ('Механический факультет', 'Механический факультет'), ('Факультет информационных технологий и экономики', 'Факультет информационных технологий и экономики'), ('Энергетический факультет', 'Энергетический факультет'), ('Заочный факультет', 'Заочный факультет'), ('Факультет сервиса', 'Факультет сервиса'), ('Факультет техносферной безопасности и права', 'Факультет техносферной безопасности и права')], max_length=255, verbose_name='Факультет')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='./profile_avatars/')),
                ('role', models.CharField(blank=True, choices=[('Администратор', 'Administrator'), ('Учитель', 'Teacher'), ('Ученик', 'Student')], default='Student', max_length=50, null=True)),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('course', models.CharField(choices=[('11', '11'), ('11', '12'), ('21', '21'), ('22', '22'), ('31', '31'), ('32', '32'), ('41', '41'), ('42', '42'), ('51', '51'), ('52', '52')], max_length=2, verbose_name='Курс')),
                ('birthday', models.CharField(max_length=10, verbose_name='Дата рождения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups', verbose_name='Группа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
                ('kurator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_kurator_group', to='main.teacher', verbose_name='Куратор')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(default='Не указано', max_length=255, verbose_name='Предметы')),
                ('teacher', models.CharField(max_length=100, verbose_name='Преподаватель')),
                ('weekday', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], verbose_name='День недели')),
                ('room', models.CharField(max_length=255, verbose_name='Аудитория')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups', verbose_name='Группа')),
                ('lesson_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lessontime', verbose_name='Время пары')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Расписание',
                'ordering': ['weekday'],
                'unique_together': {('group', 'weekday', 'lesson_time')},
            },
        ),
    ]
