# Generated by Django 5.1.4 on 2025-03-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('Администратор', 'Administrator'), ('Учитель', 'Teacher'), ('Ученик', 'Student')], default='Teacher', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='faculti',
            field=models.CharField(choices=[('Факультет топлива и экологии', 'Факультет топлива и экологии'), ('Механический факультет', 'Механический факультет'), ('Факультет информационных технологий и экономики', 'Факультет информационных технологий и экономики'), ('Энергетический факультет', 'Энергетический факультет'), ('Заочный факультет', 'Заочный факультет'), ('Факультет сервиса', 'Факультет сервиса'), ('Факультет техносферной безопасности и права', 'Факультет техносферной безопасности и права')], max_length=255, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fio',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.TextField(verbose_name='Ведущие предметы'),
        ),
    ]
