# Generated by Django 5.1.6 on 2026-02-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teacher_role_alter_teacher_faculti_alter_teacher_fio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='course',
        ),
    ]
