# Generated by Django 5.1.6 on 2026-02-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_groups_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='course',
            field=models.CharField(choices=[('11', '11'), ('11', '12'), ('21', '21'), ('22', '22'), ('31', '31'), ('32', '32'), ('41', '41'), ('42', '42'), ('51', '51'), ('52', '52')], default='11', max_length=2, verbose_name='Курс'),
        ),
    ]
